// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface FormDraft {
  /**
   * Stable questionnaire session ID
   */
  session_id: string;
  /**
   * SHA-256 hash of the client-held secret used to access this draft
   */
  draft_access_key_hash?: string;
  /**
   * Business name associated with the draft
   */
  business_name?: string;
  /**
   * Business domain associated with the draft
   */
  domain?: string;
  /**
   * Client user ID if available
   */
  user_id?: string;
  /**
   * Client user name if available
   */
  user_name?: string;
  /**
   * Client user email if available
   */
  user_email?: string;
  /**
   * Draft lifecycle status
   */
  status?: string;
  /**
   * Currently active question ID
   */
  current_question_id?: string;
  /**
   * Last changed question ID
   */
  last_changed_question_id?: string;
  /**
   * Serialized Express questionnaire responses
   */
  responses_json?: string;
  /**
   * Serialized validation status map
   */
  validation_status_json?: string;
  /**
   * Serialized touched questions map
   */
  touched_questions_json?: string;
  /**
   * Serialized expanded questions map
   */
  expanded_questions_json?: string;
  /**
   * JSON string of mapped final payload metadata
   */
  metadata_json?: string;
  /**
   * JSON string of mapped final payload userdata
   */
  userdata_json?: string;
  /**
   * JSON string of full mapped final-style Express questionnaire payload
   */
  mapped_payload_json?: string;
  /**
   * When an administrator last changed the normalized payload
   */
  payload_edited_at?: string;
  /**
   * Technical draft autosave metadata such as page path, source, app name, and user agent
   */
  draft_metadata_json?: string;
  /**
   * Latest draft save error message
   */
  save_error?: string;
  /**
   * Latest submit error payload
   */
  submit_error?: string;
  /**
   * When final submit was attempted
   */
  submit_attempted_at?: string;
  /**
   * When final submit succeeded
   */
  submitted_at?: string;
  /**
   * When the last answer changed
   */
  last_changed_at?: string;
  /**
   * When the draft was last saved
   */
  last_saved_at?: string;
  /**
   * Serialized last-known non-empty answer values used for field recovery
   */
  last_non_empty_answers_json?: string;
  /**
   * Serialized field-level answer history used for recovery
   */
  field_history_json?: string;
  /**
   * When this state was most recently persisted in the client browser
   */
  last_local_persisted_at?: string;
  /**
   * Linked final FormSubmission ID
   */
  final_submission_id?: string;
  /**
   * Status of the latest AI repair attempt. Values: not_started, diagnosed, repaired, applied, failed.
   */
  ai_repair_status?: string;
  ai_repair_attempt_count?: number;
  last_ai_repair_at?: string;
  /**
   * JSON string containing the last AI repair error.
   */
  ai_repair_error_json?: string;
  /**
   * JSON string containing AI repair diagnostics and changed paths.
   */
  ai_repair_report_json?: string;
  /**
   * JSON string containing the repaired Express payload.
   */
  ai_repaired_payload_json?: string;
  ai_repair_applied?: boolean;
  /**
   * How the repair was performed: deterministic, ai, deterministic_plus_ai, or manual.
   */
  ai_repair_source?: string;
  /**
   * Latest client submit attempt identifier persisted with this draft
   */
  submit_attempt_id?: string;
  /**
   * Short-lived compare-and-set lease token for serialized writes
   */
  idempotency_lock_token?: string;
  /**
   * Operation currently holding the serialized-write lease
   */
  idempotency_lock_key?: string;
  /**
   * Expiry for the serialized-write lease
   */
  idempotency_lock_expires_at?: string;
  /**
   * Whether this draft has moved out of the active recovery set
   */
  archived?: boolean;
  /**
   * When the draft was archived
   */
  archived_at?: string;
  /**
   * Prevents automated archival or deletion while support is investigating
   */
  active_investigation?: boolean;
  /**
   * Prevents automated archival or deletion for a legal hold
   */
  legal_hold?: boolean;
  /**
   * Prevents automated archival or deletion for an explicit retention request
   */
  retention_hold?: boolean;
}

export interface FormDraftEvent {
  /**
   * Linked questionnaire session ID
   */
  session_id: string;
  /**
   * Draft activity event type (e.g. field_change, question_opened, submit_attempted, submitted, submit_failed)
   */
  event_type?: string;
  /**
   * Question identifier
   */
  question_id?: string;
  /**
   * Question field type (e.g. checkbox, radio, textarea, geographic, numeric_range)
   */
  question_type?: string;
  /**
   * Serialized event value
   */
  value_json?: string;
  /**
   * Human-friendly value summary
   */
  value_summary?: string;
  /**
   * Value length or serialized length
   */
  value_length?: number;
  /**
   * Count of selected options or values
   */
  selected_option_count?: number;
  /**
   * Business name for the session
   */
  business_name?: string;
  /**
   * Business domain for the session
   */
  domain?: string;
  /**
   * Client user ID if available
   */
  user_id?: string;
  /**
   * Client submit attempt id used for submit diagnostics and duplicate-submit tracing
   */
  submit_attempt_id?: string;
  /**
   * When the event was created (ISO 8601)
   */
  created_at_iso?: string;
}

export interface FormSubmission {
  /**
   * Name of the business submitting the form
   */
  business_name?: string;
  /**
   * Business domain from the submission
   */
  business_domain?: string;
  /**
   * DateTime of submission in ET
   */
  submission_datetime?: string;
  /**
   * Type of service requested
   */
  service_type?: string;
  /**
   * Types of IT company selected
   */
  it_company_type?: string[];
  /**
   * Other IT company type specified
   */
  it_company_type_other?: string;
  /**
   * Primary service offerings
   */
  service_offerings?: string[];
  /**
   * Other service offerings specified
   */
  service_offerings_other?: string;
  /**
   * What makes the company different
   */
  differentiation?: string;
  /**
   * Geographic area served
   */
  geographic_areas?: string;
  /**
   * Metadata about geographic location
   */
  geographic_area_meta?: {
    label?: string;
    lat?: number;
    lon?: number;
    place_id?: string;
    source?: string;
  };
  /**
   * Pricing/packaging model
   */
  pricing_packaging?: string;
  /**
   * Other pricing model specified
   */
  pricing_packaging_other?: string;
  /**
   * Company goals for next year
   */
  company_goals?: string[];
  /**
   * Other company goals specified
   */
  company_goals_other?: string;
  /**
   * Desired brand tone
   */
  brand_tone?: string;
  /**
   * Other brand tone specified
   */
  brand_tone_other?: string;
  /**
   * Target industries served
   */
  target_industries?: string[];
  /**
   * Other industries specified
   */
  target_industries_other?: string;
  /**
   * Typical client company size
   */
  client_size?: string;
  /**
   * Main IT challenges clients face
   */
  client_challenges?: string[];
  /**
   * Other client challenges specified
   */
  client_challenges_other?: string;
  /**
   * Desired client outcomes
   */
  client_outcomes?: string[];
  /**
   * Other client outcomes specified
   */
  client_outcomes_other?: string;
  /**
   * Description of ideal client
   */
  ideal_client?: string;
  /**
   * Complete raw questionnaire response snapshot retained without requiring authentication
   */
  raw_responses_json?: string;
  /**
   * Complete normalized submission payload snapshot
   */
  transformed_payload_json?: string;
  /**
   * Stable questionnaire recovery/session id
   */
  questionnaire_session_id?: string;
  /**
   * Client submit attempt id used for idempotency and diagnostics
   */
  submit_attempt_id?: string;
  /**
   * Delivery status for the downstream Express Zapier webhook
   */
  zapier_delivery_status?: "not_attempted" | "sent" | "failed";
  /**
   * Whether the downstream Express Zapier webhook was successfully delivered
   */
  zapier_sent?: boolean;
  /**
   * ISO timestamp when Zapier delivery succeeded
   */
  zapier_sent_at?: string;
  /**
   * Safe serialized Zapier delivery error if delivery failed
   */
  zapier_error_json?: string;
  /**
   * Number of Zapier delivery attempts for this submission
   */
  zapier_attempt_count?: number;
  /**
   * Number of times this submission has been resubmitted to Zapier via admin retry
   */
  resubmit_count?: number;
}

export interface FormSubmissionIntake {
  /**
   * Questionnaire session identifier used for recovery and deduplication
   */
  questionnaire_session_id: string;
  /**
   * Client submit attempt id used for idempotency and support diagnostics
   */
  submit_attempt_id?: string;
  /**
   * Business name from the submission
   */
  business_name?: string;
  /**
   * Business domain from the submission
   */
  business_domain?: string;
  /**
   * User email if available
   */
  user_email?: string;
  /**
   * User ID if available
   */
  user_id?: string;
  /**
   * Lifecycle status of the intake record
   */
  status?:
    | "submitted"
    | "received_intake"
    | "auto_repair_pending"
    | "retry_pending"
    | "retry_success"
    | "retry_failed"
    | "abandoned";
  /**
   * Reason this intake record was created (e.g. form_submission_create_failed, payload_transform_failed)
   */
  intake_reason?: string;
  /**
   * Classified kind of the primary failure (e.g. timeout, network, server)
   */
  primary_failure_kind?: string;
  /**
   * Classified kind of the fallback failure if fallback also failed
   */
  fallback_failure_kind?: string;
  /**
   * Serialized primary error context
   */
  primary_error_json?: string;
  /**
   * Serialized fallback error context
   */
  fallback_error_json?: string;
  /**
   * Serialized error from the most recent retry attempt
   */
  retry_error_json?: string;
  /**
   * Serialized transformed Express payload at time of intake
   */
  transformed_payload_json?: string;
  /**
   * Serialized raw Express questionnaire responses
   */
  raw_responses_json?: string;
  /**
   * Serialized diagnostic metadata (browser, timing, context)
   */
  diagnostics_json?: string;
  /**
   * Source context that triggered the intake (e.g. questionnaire_submit_fallback)
   */
  source?: string;
  /**
   * ISO timestamp from the client at time of intake trigger
   */
  created_at_client?: string;
  /**
   * ISO timestamp recorded by the server function
   */
  created_at_server?: string;
  /**
   * ISO timestamp of the last retry attempt
   */
  last_retry_at?: string;
  /**
   * Number of retry attempts made
   */
  retry_count?: number;
  /**
   * FormSubmission record ID if a final submission was successfully created
   */
  linked_submission_id?: string;
  /**
   * Whether a Zapier delivery has been triggered for this intake
   */
  zapier_sent?: boolean;
  /**
   * Serialized Zapier delivery error if zapier_sent failed
   */
  zapier_error_json?: string;
  /**
   * Admin notes for manual recovery tracking
   */
  notes?: string;
  /**
   * Status of the latest AI repair attempt. Values: not_started, diagnosed, repaired, retried, applied, failed.
   */
  ai_repair_status?: string;
  ai_repair_attempt_count?: number;
  last_ai_repair_at?: string;
  /**
   * JSON string containing the last AI repair error.
   */
  ai_repair_error_json?: string;
  /**
   * JSON string containing AI repair diagnostics and changed paths.
   */
  ai_repair_report_json?: string;
  /**
   * JSON string containing the repaired Express payload.
   */
  ai_repaired_payload_json?: string;
  ai_repair_applied?: boolean;
  ai_repair_retry_attempted?: boolean;
  /**
   * JSON string containing the result of a retry attempt after AI repair.
   */
  ai_repair_retry_result_json?: string;
  /**
   * How the repair was performed: deterministic, ai, deterministic_plus_ai, or manual.
   */
  ai_repair_source?: string;
  /**
   * Whether this intake has moved out of the active recovery set
   */
  archived?: boolean;
  /**
   * When the intake was archived
   */
  archived_at?: string;
  /**
   * Prevents automated archival or deletion while support is investigating
   */
  active_investigation?: boolean;
  /**
   * Prevents automated archival or deletion for a legal hold
   */
  legal_hold?: boolean;
  /**
   * Prevents automated archival or deletion for an explicit retention request
   */
  retention_hold?: boolean;
}

export interface SubmissionPdfVersion {
  /**
   * FormDraft record that owns this saved PDF version
   */
  draft_id: string;
  /**
   * Stable questionnaire session ID
   */
  questionnaire_session_id?: string;
  /**
   * FormSubmission record used for this PDF, when available
   */
  submission_id?: string;
  /**
   * Submit attempt ID represented by this PDF
   */
  submit_attempt_id?: string;
  /**
   * SHA-256 fingerprint of all values rendered into the PDF
   */
  payload_hash: string;
  /**
   * Payload source used for generation, such as mapped_payload_json or form_submission
   */
  payload_source?: string;
  /**
   * Deprecated legacy payload snapshot; new versions store only payload_hash
   */
  payload_json?: string;
  /**
   * Timestamp of the source draft or submission used for generation
   */
  source_updated_at?: string;
  /**
   * Deprecated legacy public URL; migrated versions use pdf_file_uri
   */
  pdf_file_url?: string;
  /**
   * Base44 private file URI; never sent directly to the browser
   */
  pdf_file_uri?: string;
  /**
   * Storage protection state for this PDF version
   */
  storage_visibility?: "private" | "legacy_public";
  /**
   * Unique logical key composed from draft, payload hash, and template version
   */
  idempotency_key?: string;
  /**
   * Download filename for this PDF
   */
  pdf_filename: string;
  /**
   * Generated PDF file size in bytes
   */
  pdf_byte_size?: number;
  /**
   * Version of the Express PDF template used
   */
  template_version: string;
  /**
   * Monotonically increasing version number within the draft
   */
  version_number: number;
  /**
   * Business name rendered in the PDF
   */
  business_name?: string;
  /**
   * Business domain rendered in the PDF
   */
  business_domain?: string;
  /**
   * When this PDF version was generated and saved
   */
  generated_at?: string;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "FormDraft": FormDraft;
    "FormDraftEvent": FormDraftEvent;
    "FormSubmission": FormSubmission;
    "FormSubmissionIntake": FormSubmissionIntake;
    "SubmissionPdfVersion": SubmissionPdfVersion;
  }
  
  interface FunctionNameRegistry {
    "draftPdfStorage": true;
    "draftRecoveryRetention": true;
    "autoRepairRetryIntake": true;
    "draftRecoveryData": true;
    "questionnaireDraftData": true;
    "retryQuestionnaireIntakeSubmission": true;
    "repairExpressQuestionnaireIntakeSubmission": true;
    "submitExpressAdminIntake": true;
    "submitExpressQuestionnaireFallback": true;
    "validateExpressQuestionText": true;
    "sendExpressToZapier": true;
    "verifyDraftRecoveryAccess": true;
  }
  
  interface AgentNameRegistry {
    "express_submission_repair_agent": true;
  }
}